<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="asml" type="stateSpaceDocument"/>

  <xs:complexType name="stateSpaceDocument">
    <xs:sequence>
      <xs:element name="state_space" type="stateSpaceType"/>
	  <xs:element name="final_marking" type="markingType"/>
      <xs:element name="transitions" type="transitionsType"/>
      <xs:element name="variables" type="variablesType"/>
    </xs:sequence>
  </xs:complexType>

  <!-- State Space definition -->
  <xs:complexType name="stateSpaceType">
    <xs:sequence>
      <xs:element name="states" type="statesType"/>
      <xs:element name="arcs" type="arcsType"/>
    </xs:sequence>
    <xs:attribute name="graph_type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="AbstractReachabilityGraph"/>
          <xs:enumeration value="AbstractCoverabilityGraph"/>
          <xs:enumeration value="AbstractCoverabilityTree"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="is_full" type="xs:boolean" use="required"/>
  </xs:complexType>

  <xs:complexType name="statesType">
    <xs:sequence>
      <xs:element name="state" type="stateType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="stateType">
    <xs:sequence>
      <xs:element name="marking" type="markingType"/>
      <xs:element name="constraint" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" use="required"/>
  </xs:complexType>

  <xs:complexType name="arcsType">
    <xs:sequence>
      <xs:element name="arc" type="arcType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="arcType">
    <xs:attribute name="label" type="xs:string" use="required"/>
    <xs:attribute name="is_silent" type="xs:boolean" use="required"/>
    <xs:attribute name="source_id" type="xs:integer" use="required"/>
    <xs:attribute name="target_id" type="xs:integer" use="required"/>
    <xs:attribute name="base_transition_id" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="markingType">
    <xs:sequence>
      <xs:element name="place" type="placeType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Place in final marking -->
  <xs:complexType name="placeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="tokens" type="xs:integer" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Transitions collection -->
  <xs:complexType name="transitionsType">
    <xs:sequence>
      <xs:element name="transition" type="transitionType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Individual transition -->
  <xs:complexType name="transitionType">
    <xs:sequence>
      <xs:element name="name">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="text" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="base_transition_id" type="xs:string" use="required"/>
    <xs:attribute name="is_tau" type="xs:boolean" use="required"/>
    <xs:attribute name="is_split" type="xs:boolean" use="required"/>
    <xs:attribute name="guard" type="xs:string" use="optional"/>
  </xs:complexType>

  <!-- Variables collection -->
  <xs:complexType name="variablesType">
    <xs:sequence>
      <xs:element name="variable" type="variableType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Individual variable -->
  <xs:complexType name="variableType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Real"/>
          <xs:enumeration value="Boolean"/>
          <xs:enumeration value="Integer"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

</xs:schema>